export const HANDLE_TOGGLE_QUESTION = 'HANDLE_TOGGLE_QUESTION';
export const HANDLE_NEXT_QUESTION = 'HANDLE_NEXT_QUESTION';
export const HANDLE_RESTART_QUIZ = 'HANDLE_RESTART_QUIZ';
export const HANDLE_VALIDATE_ANSWER = 'HANDLE_VALIDATE_ANSWER';
